# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
inhibit_all_warnings!

pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

pod 'React', :subspecs => [
  'Core',
  'RCTBlob',
  'RCTAnimation',
  'RCTActionSheet',
  'RCTGeolocation',
  'RCTImage',
  'RCTLinkingIOS',
  'RCTNetwork',
  'RCTSettings',
  'RCTText',
  'RCTVibration',
  'RCTWebSocket',
  'BatchedBridge',
  'DevSupport',
  'ART',
  'RCTCameraRoll',
  'RCTPushNotification',
  'RCTTest',
], :path => '../node_modules/react-native'

target 'DEMOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for DEMOS
  target 'DEMOSTests' do
  end

end

